spring.application.name=Eventgest

# Habilitar Docker Compose (opcional)
spring.docker.compose.enabled=false


# Datos de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/eventgest
spring.datasource.username=postgres
spring.datasource.password=fabrica2024*
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


