spring.application.name=Eventgest
server.port=8080

# Habilitar Docker Compose (opcional)
spring.docker.compose.enabled=false




# Datos de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/eventgest
spring.datasource.username=postgres
spring.datasource.password= fabrica2024*
  # 10Sofia2
  # fabrica2024*
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#langchai4j
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

